#!/bin/bash

#The following script install all markdown images (only links)

set -e

if [ ! "$#" -eq 1 ]; then
    echo "Usage: $0 input.md"
    exit 1
fi 

if [[ $1 == *.md || $1 == *.txt ]]; then
    echo "The file is valid"
else
    echo "The file is neither markdown or text"
    exit 1
fi

links=$(grep -oP "!\[[^\]]*\]\(\K[^)]*(?=\))"  $1)

for i in "$links"; do
    wget $i
done
